version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: php_container
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agency_x_users
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

volumes:
  db_data:
